### ISSUE TITLE
Resuming model training

### ISSUE THREAD

**Issue by cgaletzka** [cabooster/DeepCAD-RT#10]
Hi, I ran out of disk space while training a model on my own data. Could you please let me know how I could resume training from the last epoch that was saved?

**Comment by cabooster** [comment]
This issue is similar to the solved problem in [Pytorch Tutorial](https://pytorch.org/tutorials/recipes/recipes/saving_and_loading_a_general_checkpoint.html). You can refer to the tutorial in this link.
