### ISSUE TITLE
Oversaturated ROIS and activity traces

### ISSUE THREAD

**Issue by eltabbal** [cabooster/DeepCAD-RT#11]
Thanks alot for DEEPCAD. i ran into a couple of issues 
1) in some ROIs, deepcad tends not to produce the same trace I see on the raw data (especially in the peak) , i am attaching a picture of ROI trace (peakdips.png)
![peakdips](https://user-images.githubusercontent.com/22963512/164155091-07874fc6-36f9-43e1-a2d6-f56ceec9cc62.png)

2) in some oversaturated ROIs with high activity, the ROI turns dark in the movie and this translates into a dip in the data , i am also attaching an example (oversturateddips.png) . 
![oversaturateddip](https://user-images.githubusercontent.com/22963512/164155095-8a0ce1da-842e-44af-a0a0-b25e91f5fbfb.png)

3) It is not clear to me, what is the data size parameter ( is it the number of slices in all your recordings in the folder or the number of patches in all your recordings )
i had two tiff files each 1000 frame to train on ; i used the following parameters
n_epochs = 10               
GPU = '0'                   
train_datasets_size = 2000  
patch_xy = 150             
patch_t = 150               
overlap_factor = 0.25       
num_workers = 0             

![deepcadoversaturate](https://user-images.githubusercontent.com/22963512/164156561-99b4824a-ee7d-4062-9096-2c1397fbaa3d.gif)

**Comment by cabooster** [comment]
Hi, eltabba. Thanks for your feedback! Since saturation should be avoided during imaging by adjusting the amplifier or the excitation power, oversaturated data was not investigated in our work. We think these two problems may derive from the same issue, most likely from data formatting result storage. We will try some oversaturated data to fix it as soon as possible and reply you once it is solved. Additionally, if you could share these data with us, that's would be really helpful.

**Comment by cabooster** [comment]
Thanks for your sharing! We are now working on your data to solve this issue. 

Sorry about omitting your third question. `train_datasets_size` means how many 3D patches (150x150x150 pixels) will be extracted from the input stacks for network training. Actually, `train_datasets_size` could be fixed to 6000 according to our experience. We used data augmentation to make small dataset training feasible. If there are a large number of training frames and you want the network to see as much data as possible, `train_datasets_size` can be roughly estimated by
`image_width`x`image_height`x`total_frame_number_of_all_stacks`/(`patch_xyt`x(1-`overlap_factor`))<sup>3</sup>.

**Comment by cabooster** [comment]
We found this issue attributed to the output data storage format. We have updated the pip release of DeepCAD-RT [pypi](https://pypi.org/project/deepcad/)  and GitHub code. Please type `pip install deepcad==0.6.4` to upgrade the pip package and try again.

**Comment by eltabbal** [comment]
I think the issue is solved, I will run one more data set to confirm everything is fine but in general, looks very good now. thanks a lot.
