### ISSUE TITLE
input number of frames is not equal to output frame numbers ( file size around 4 GB) 

### ISSUE THREAD

**Issue by eltabbal** [cabooster/DeepCAD-RT#12]
Thanks again for the amazing package, in the new version deepcad==0.6.4 , if the input file has 8170 frames the output gives you only 8000 frames i think it has something to do with the saving options after the recent update.

**Comment by eltabbal** [comment]
to debug it easily i am providing a model i trained with some data check this link 
https://www.dropbox.com/sh/dl5k4tl85fez9kj/AABRrbeFAxr-gt23kbm9IuG6a?dl=0

**Comment by cabooster** [comment]
We tried the uploaded file but no problems were found. We suspect that you set the `test_datasize` to 8000. `test_datasize` is the number of slices to be tested. According to your training parameters and your requirement, the inference parameters should be set as follows in `demo_test_pipeline.py`:

- `test_datasize` = 8178
- `patch_xy` = 128
- `patch_t` = 128

**Comment by cabooster** [comment]
We tried your file but no problems were found. Maybe you set the `test_datasize` to 8000? `test_datasize` means how many frames to test. If it is larger than the number of frames in your stack, all frames will be processed. You can set it as a very large number if all frames must be tested.

**Comment by eltabbal** [comment]
Thanks a lot, I think you use different definitions of the term "datasize". In the training,  it is the number of 3D patches to train on, and in testing, it is the number of slices.
