### ISSUE TITLE
Split data-set to conserve memory, uneven baselines in consecutive stacks

### ISSUE THREAD

**Issue by Sverreg** [cabooster/DeepCAD-RT#13]
I split my data-set to avoid exceeding memory capacity, as suggested in Issue #3. This appears to have resulted in uneven denoising? See below a screenshot from Suite2P on the processed stacks.

![image](https://user-images.githubusercontent.com/27206049/167130541-7e6fe9ca-a6f3-43b2-ac7d-edbe57e36df7.png)

The model was trained on a subset of the same data for 35 epochs, using default settings. Please let me know what additional information you need to troubleshoot.

**Comment by cabooster** [comment]
Hi, Sverreg. Thanks for your feedback! If you could share about 8000 frames of your data and model file (`.pth` and `.yaml`) with us, that's would be helpful.

**Comment by Sverreg** [comment]
Hi Cabooster,

[This Drive folder](https://drive.google.com/drive/folders/16Ie9PqCKzVpnd4Oxcyd264joVEUgLXYt?usp=sharing) includes 5x1850 frames, and the model I used to generate the data illustrated in this issue. I used the first 1000 frames for training.

From script.py:
![image](https://user-images.githubusercontent.com/27206049/167414504-4f861035-4b91-4716-ba34-bf17f0388eb2.png)

**Comment by cabooster** [comment]
Thanks for your sharing! 

We tried your file but no problems were found. The results are illustrated below. Maybe you used the old version of DeepCAD-RT. We suggest you download the current version according to the [tutorial ](https://cabooster.github.io/DeepCAD-RT/Tutorial/)and try again. 

![4ad5015dda395799631144d9a6bd3a7](https://user-images.githubusercontent.com/71710781/167569853-08173ead-1acb-4304-8643-2e87597d7803.png)

In addition,  `train_datasets_size` means how many 3D patches (150x150x150 pixels) will be extracted from the input stacks for network training. This parameter could be fixed to 6000 according to our experience, and 10 epochs are enough in most situations.

**Comment by Sverreg** [comment]
Yupp, I used an old version. I updated to the most recent version now and everything works as expected, thanks!
