### ISSUE TITLE
inference data requires adjacent frames similar？

### ISSUE THREAD

**Issue by Wolfwjs** [cabooster/DeepCAD-RT#18]
Hi, When inference, does stack.tiff need to satisfy the requirement that the signals of two adjacent frames are similar? 
For example, different positions of cells are shot, and only one frame is shot at each position.

**Comment by cabooster** [comment]
Hi, Wolfwjs. According to our experience, the inference process has lower requirements on temporal continuity. In some applications, we trained models on high frame rates and used them to denoise data with much lower frame rates. But when the frame rate is too low, the performance will be affected. It's better to try it to decide whether it can be applied to your data.

**Comment by Wolfwjs** [comment]
Thank you for your reply! I'll give it a try
