### ISSUE TITLE
real-time implementation

### ISSUE THREAD

**Issue by Wolfwjs** [cabooster/DeepCAD-RT#19]
Hi, I have the following questions about the real-time performance in the actual process of image acquisition:

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/36124147/202430505-6c013106-3476-496c-8f12-ede1cdda6d3e.png">

1. What is the frame rate of the microscope in above figure? 
2. Approximately how many similar pictures will be generated for each position？Because I have considered whether it is difficult to meet the condition that adjacent frames are similar because it is dynamic.
3. What is the latency of each stage from image acquisition to processing to display ？

Looking forward to your reply, thank you!

**Comment by cabooster** [comment]
Hi @Wolfwjs!
1. 30HZ
2. Similar pictures are randomly generated from the input frame. Adjacent frames don't have to be exactly similar. The structure is basically similar is required. A little movement is acceptable. For detail, you can download [our data](https://cabooster.github.io/DeepCAD-RT/Datasets/) and observe the difference between adjacent frames. 
3. The latency depends on your GPUs and the parameters in the advanced setting. The overall latency with our experimental setting is ~4s. The latency (annotated with a red arrow) can be calculated according to the below figure.

![image](https://user-images.githubusercontent.com/71710781/202647853-230ddcaf-df0f-418b-89ad-978503a404ed.png)

**Comment by Wolfwjs** [comment]
Thank you very much for your patient reply!
