### ISSUE TITLE
freeze support

### ISSUE THREAD

**Issue by gorillaleap** [cabooster/DeepCAD-RT#2]
Hi, sorry for the problem. When I am trying to run the code 'python script.py test', there is a RuntimeError. But I didn't find 'freeze_support' function in the test.py.
![image](https://user-images.githubusercontent.com/88165643/130806130-9770fe99-18f3-412e-9301-54cc35037ca1.png)

**Comment by cabooster** [comment]
I am sorry that I reply you late. The reason for this error is that you use the Windows system to run our script, and the num_worker should be set to 0. Good news! We update the DeepCAD-RT version, and this parameter is easy to edit.
