### ISSUE TITLE
Request for clarifiations on image format and train parameters

### ISSUE THREAD

**Issue by NBCS1** [cabooster/DeepCAD-RT#21]
Hello, 

I manage to train and test your model on the fish_localbrain.tiff example stack.
However, when I try with some data laying around, I had a movie with 1 channel, 25 timeframes (25,515,515), it does not work and I keep getting error such as :
`UserWarning: Using a target size (torch.Size([1, 1, 13, 492, 492])) that is different to the input size (torch.Size([1, 1, 12, 492, 492])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
` and `RuntimeError: The size of tensor a (12) must match the size of tensor b (13) at non-singleton dimension 2`.

I tried to reduce my stack to (25,492,492) same xy as the fish stack, just by curiosity, same.
Then I actually reduced your stack to 25 frames (with FIJI, saved as a tiff file) and I have the same kind of error.
Then, I played on the parameters 
train_datasets_size 
patch_xy 
patch_t 
overlap_factor

However, I'm not familiar with Pytorch and I don't really understand what these parameters stand for.

In some cases it does actually manages some batches (less than 10) but then I get this kind of error
`RuntimeError: Given input size: (64x1x123x123). Calculated output size: (64x0x61x61). Output size is too small`

Could you clarify how to properly set the parameters according to the shape of the stack to be train on?
Is it a FIJI saving problem? I check your file and my file by reading them with tifffile.imread and the shapes are good (TXY format).
Because I tried to open your original file and save it back with FIJI, seems to be working fine but I had this error though:
`<tifffile.TiffPage 0 @8> imagej_metadata failed with ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
`
Is it because they are too little timeframes? I tried the fish example at 1000 frames and same kind of error. I tried to duplicate my stack until I had a loop with >7000 frames and it seems to work.

Thank you

**Comment by cabooster** [comment]
Hi! 
In most cases, the following default parameter setting can work. You do not need to change it.

![image](https://user-images.githubusercontent.com/71710781/219538557-2965683b-8b91-4627-bfbf-b1b13b96cd48.png)

But due to the feature of our network, the input time frames should be larger than 1000. If the input frames in x/y/t dimensions are limited, it is possible to get an error. Then you can decrease the `train_datasets_size` to 5500 or 5000.

**Comment by cabooster** [comment]
Hi, here are some more specific explanations.

DeepCAD-RT was designed for time-lapse imaging, not for single-image denoising. Thus the image stacks (xy-t) used for training should have many frames. When the patch size is 150, the stacks should have at least 150 frames or more. Usually, our training stacks have more than 500 frames. Errors will occur if there are too few frames to extract image patches.

If you have any questions, please feel free to contact me.

**Comment by peterbartlett64** [comment]
Hello,
I have a similar issue and would like to denoise multiple similar time series ranging from 60-120 frames with 2048x2048 pixels. 

Is your program incompatible with my requirements?

Are non-cubic tensors accepted -  eg. 150x-150y-60t? 

I have run into numerous error codes and would appreciate any information/recommendations for tensor parameters and 'train_datasets_size'

**Comment by cabooster** [comment]
As mentioned before, the number of training frames is recommended to be more than 500 frames. If the input frame number is not enough, the results won't be satisfying. You can try to capture longer frames and try again.
