### ISSUE TITLE
Images on bottom and top of the stack yield unexpected output, unable to find root cause

### ISSUE THREAD

**Issue by z-pan** [cabooster/DeepCAD-RT#26]
When I send a stack of microscopy images into the model, the images on the bottom and the top of the stack appear with extremely high overall intensity (please refer to the following images). But the images in the middle seem fine. 
The input and corresponding output at the top of the stack:
![image](https://github.com/cabooster/DeepCAD-RT/assets/12038796/807d1173-298e-4437-bce0-c6317e1d35cb)
The input and corresponding output at the bottom of the stack:
![image](https://github.com/cabooster/DeepCAD-RT/assets/12038796/723df0d9-a005-43d9-b983-06cc24d2be88)

The hyper-parameters are the following:
test_datasize = 601
patch_xy = 150
patch_t = 100
overlap_factor = 0.6

Also, I tried inputting only the 300 frames in the middle of the original stack, which has 601 frames, the output does not have the above problem. 

I wonder what could be the possible cause. Is it because the overall intensity of the top and bottom images highly differ from that of the images in the middle? Or it has something to do with the pre-processing step of subtracting the mean (i.e. the code shown in the image below)?
![image](https://github.com/cabooster/DeepCAD-RT/assets/12038796/5910c905-204a-4450-9100-2854cddb6eba)

Much appreciated!

**Comment by cabooster** [comment]
Hi!
1. Do you train your own model using these noisy stacks?
2. as the pre-processing step, we subtract the mean value but we add it back as the post-processing step. I cannot determine the specific cause based on the current information. I hope you can provide me with your model file (.pth), training parameters, and data to help you resolve the issue.

**Comment by z-pan** [comment]
Hi, thanks for the reply!

1. Yes I trained my own model. But I do not think this problem is caused by training, since the pre-trained model "fish_wholebrain" yields the same problem on my test data.
2. I see. I found your email address in Issue#22, can I send the model file and data to this email address?

**Comment by z-pan** [comment]
Following up on my latest comment, is 22110720036@m.fudan.edu.cn the correct email address? (found it in Issue#22)
Apologies for constantly bugging you 🙏

**Comment by cabooster** [comment]
I tried to convert the .npy file to .tif file and denoise the first volume (512x512x300) using the model and parameter you offer. I didn't find any issues with intensity variations. The mean values of the input and output images are nearly identical.
Intensity comparison:
![image](https://github.com/cabooster/DeepCAD-RT/assets/71710781/74631ae9-2d9a-429e-8008-82562bdfb0b1)
my code:
![image](https://github.com/cabooster/DeepCAD-RT/assets/71710781/9b13b23a-0cd8-45d8-9ac5-d1d01b7e50e5)

**Comment by z-pan** [comment]
I see, thank you very much! I modified the code on subtracting and adding back the mean value, and I realize the cause might be the following: within a patch volume that contains the frames that have the said problem, the mean values of certain frames differ too much from those of the other frames, which results in the overall intensity of the frames with originally low intensity to be raised to a higher level. In a word, there might be additional processing needed to deal with patches that contain frames with largely different overall intensities. 
Do you think it is a reasonable speculation?

**Comment by cabooster** [comment]
I think your speculation is correct. The data we used in our experiments are temporal data, and the method relies on the assumption that consecutive frames capture independent noise of similar objects, meaning that the mean values of each frame are roughly the same. However, in your data, each frame consists of a single layer in the z dimension instead of the t dimension. This might be a reason why our method is encountering issues with your data.
