### ISSUE TITLE
Pytorch using CPU when running demo_train_pipeline.py

### ISSUE THREAD

**Issue by claudioez** [cabooster/DeepCAD-RT#27]
Hi,

thanks a lot for this great application, I am looking forward to use it.

After updated anaconda, used python 3.9, upgraded Pip and finally installed it (in order to avoid issues when the deepcad installation routine was attempting to build wheels for OpenCV) I got to the level that the demo_train_pipeline is running.

But I am surprised that pytorch uses the GPU memory (RTX 3060) but also  35% of the CPU  power (AMD Ryzen 7 3700X)-

I wonder if this behavior is expected, because it would take around 6 hours to run the training demo.

Thanks in advance, Claudio-

**Comment by cabooster** [comment]
The default number of training epochs is 10, and the time consumption is reasonable when running on a 3060 GPU.
