### ISSUE TITLE
High loss on demo training

### ISSUE THREAD

**Issue by oscarwooberry** [cabooster/DeepCAD-RT#29]
![image](https://github.com/cabooster/DeepCAD-RT/assets/44183898/80459899-81e9-4dcb-b258-2cd53f8a3ffe)
I have this very high training loss on demos, is that normal? everything is the default.

**Comment by cabooster** [comment]
Hello! This is a normal phenomenon. The larger loss value is related to the principle of unsupervised training. Specifically, the model predicts the next frame to tend towards a denoised image, so there will always be a significant difference between the predicted next frame and the actual next frame.

**Comment by oscarwooberry** [comment]
Thank you so much for answering my question!
