### ISSUE TITLE
Colab notebook not working

### ISSUE THREAD

**Issue by rchereau** [cabooster/DeepCAD-RT#30]
Hello,

I tried a few times to run the Colab notebook without changing anything in the script.
I enabled the T4 GPU in the parameters before starting.
It crashes at the end of the first epoch of the training.
Could you please help to fix that?

**Comment by cabooster** [comment]
I haven't encountered this problem before. It could be due to network fluctuations. Please check your network connection. If there is a disruption in the network, the training process may be terminated. If it's not the case, please provide me with the specific error message.

**Comment by rchereau** [comment]
Thanks for your reply.
The error showed up both at work and at home, so I don't think it's network related.

Here is the error during: tc.run()

Image list for training -----> 
Total stack number ----->  1
Noise image name ----->  fish_localbrain.tif
Noise image shape ----->  (2000, 492, 492)
Using 1 GPU(s) for training -----> 
[Epoch 1/2] [Batch 2096/2096] [Total loss: 43382.02, L1 Loss: 201.46, L2 Loss: 86562.57] [ETA: 0:32:09] [Time cost: 1924 s]      
 ============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

[<ipython-input-11-e3a69145da7f>](https://localhost:8080/#) in <cell line: 1>()
----> 1 tc.run()

5 frames

[/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/onnx_proto_utils.py](https://localhost:8080/#) in _add_onnxscript_fn(model_bytes, custom_opsets)
    226     # serialization anyway in terms of the protobuf limitation. So we don't
    227     # need to worry about > 2GB model getting here.
--> 228     model_proto = onnx.load_from_string(model_bytes)
    229 
    230     # Iterate graph nodes to insert only the included custom

AttributeError: module 'onnx' has no attribute 'load_from_string'

**Comment by cabooster** [comment]
I apologize for the confusion. It's not actually a network issue. I have made some modifications to the code and upgraded the pip package to version 1.0.0. You can now try again, and it should work fine.

**Comment by rchereau** [comment]
Thanks for the update.
I managed to perform a training.
Now I would like to test the created model using option 2 but it seems that it's not looking in the right place to load the model.
Thanks in advance for your help.

Here is the error I get in 

tc.run()
---------------------------------------------------------------------------

FileNotFoundError                         Traceback (most recent call last)

[<ipython-input-76-e3a69145da7f>](https://localhost:8080/#) in <cell line: 1>()
----> 1 tc.run()

1 frames

[/usr/local/lib/python3.10/dist-packages/deepcad/test_collection.py](https://localhost:8080/#) in prepare_file(self)
     98         self.output_path = self.output_dir + '//' + 'DataFolderIs_' + self.datasets_name + '_' + current_time + '_ModelFolderIs_' + self.denoise_model
     99         if not os.path.exists(self.output_path):
--> 100             os.mkdir(self.output_path)
    101 
    102     def set_params(self, params_dict):

FileNotFoundError: [Errno 2] No such file or directory: './results//DataFolderIs_TEMP_202306221300_ModelFolderIs_/content/pth/TEMP_202306221128'


The folder paths that I did set above are:
datasets_path = '/content/drive/MyDrive/TEMP'       # folder containing all files to be tested
denoise_model = '/content/pth/TEMP_202306221128' # A folder containing models to be tested

**Comment by cabooster** [comment]
`denoise_model` should be set as the denoise model subfolder name, for example: 'TEMP_202306221128'. Because the default location for the model is in the './pth' folder.

**Comment by rchereau** [comment]
Thank you very much for your help!
