### ISSUE TITLE
the input tiff is 5000 frames but the output is 2500

### ISSUE THREAD

**Issue by GUO-neuroLAB** [cabooster/DeepCAD-RT#31]
hi i train the model on my own data, but the input 5000 frames tiff file ,output 2500, i set the paramether datasetsize to 100000,as default, which is larger than the 5000. how can i cope with it? thanks a lot

**Comment by cabooster** [comment]
After examining the code with the data you provided, it was found that the issue originates from the data collection process, not the code itself. It's possible that you need to investigate the source of the problem on your end.

**Comment by GUO-neuroLAB** [comment]
thankyou
