### ISSUE TITLE
Parameters get overwritten by yaml from model

### ISSUE THREAD

**Issue by kaymvoit** [cabooster/DeepCAD-RT#4]
In test.py line 63, some options are loaded from the para.yaml of the model. I cannot judge if that makes sense for some of those options (but why are they even there as flags in the first place, then?), but I think I can safely say that for the output path, this behavior is undesirable.

**Comment by cabooster** [comment]
I think you can remove this line `read_yaml(opt, model_path + '//' + yaml_name)`

**Comment by kvoit** [comment]
Thanks!
