### ISSUE TITLE
Visible tiling with custom training data

### ISSUE THREAD

**Issue by kaymvoit** [cabooster/DeepCAD-RT#5]
I have tested a training on our own data with
```
python train.py --datasets_folder training --datasets_path /gpfs/soma_fs/home/voit/data/2gfs --n_epochs 40 --GPU 0,1,2,3 --batch_size 4 --train_datasets_size 5000 --select_img_num 1000000
```
where the respective folder contained 25 recordings of approx 3000 frames each. 
I then ran the denoising using
```
test.py --output_dir "${OUTPUT_DIR}" --denoise_model "$DENOISE_MODEL" --datasets_path "$DATASET_PATH" --datasets_folder "$DATASET_FOLDER" --batch_size 4 --test_datasize 100000 --GPU 0,1,2,3
```

We observe two things with this:

1. The denoised results are notably less detailed compared to denoising with the provided ModelForPytorch. In the latter, dendrites are clearly visible, while with our training, frames remain quite blurry. In our training, with "to many" epochs, we just start to see feature of few pixels that don't seem physiologically convincing.
2. There is visible tiling in the results, which I do not see with the provided training.

Are there any recommendation how to improve this situation?

**Comment by cabooster** [comment]
Hi, kaymvoit. Which epoch did the model you tested come from? Generally, the network will be trained from 'underfitting' to 'fitting' then to 'overfitting'. For the best performance, you should use the best model that is neither underfitting nor overfitting. You can do that by testing all the models on a small `--test_datasize` (for example 300). According to my experience, underfitting models seem to be blurry and have visible tiling.

**Comment by kvoit** [comment]
I checked all 40 epochs that the train script generates. For us, the tiling is especially visible for higher epochs, starting to become notable between around E15, when the data still looks relatively blurry.
For epochs over 15-20, the data is less blurry, but does not show the same amount of physiologically convincing detail that we see with the provided training.

Here are some examples:

Custom, E10:
![custom-E10](https://user-images.githubusercontent.com/1532745/133389763-5feaff60-0f76-4a0a-a6e1-e43006f23f95.png)

Custom, E12 (bottom increased contrast, red is clipped):
![custom-E12](https://user-images.githubusercontent.com/1532745/133389768-9e01a46a-6fc8-40f2-9b19-f9bd588bb534.png)
![custom-E12-hc](https://user-images.githubusercontent.com/1532745/133389766-b406190d-2793-4896-a6c4-0b8d5e9f174f.png)

Custom, E20:
![custom-E20](https://user-images.githubusercontent.com/1532745/133389771-ec6cf3f6-ace9-4206-802a-d8a4e333a25c.png)

Custom, E30:
![custom-E30](https://user-images.githubusercontent.com/1532745/133389772-579018ef-b290-4800-9ee9-d96dd122b9c8.png)

Custom, E40:
![custom-E40](https://user-images.githubusercontent.com/1532745/133389773-ba973711-c8d7-4511-8637-4365624495c9.png)

Provided ModelForPytorch, E10 (bottom increased contrast, red is clipped):
![provided-E10](https://user-images.githubusercontent.com/1532745/133389777-d54baab9-cd37-4f34-9559-77089c5147a2.png)
![provided-E10-hc](https://user-images.githubusercontent.com/1532745/133389774-eb34d15a-dabf-42a0-83ff-b06a5e2eed45.png)

In general, I would already be satisfied with E10 or E12, but I wonder why the provided training ilooks so much better. Given that for higher epoch numbers, the network also comes up with thin structures on the soma, is it imaginable that the drendrites around the soma are also artifacts from the network?

**Comment by cabooster** [comment]
For most deep neural networks, the training data determinate their performance. I notice that your training set has 25 recordings. We usually did not use so much training data. Whether there's too much diversity in the data?

Since the training data we used had soma and dendrites, using it on other data would likely bring similar structures. As you know, DNNs will learn priors from the training data. Thus, the safest way is to train a model separately for each set of data. We are now working on it to make it a structure-independent and more versatile tool.

I hope these are helpful for you.
