### ISSUE TITLE
TifffileError: not a TiFF file

### ISSUE THREAD

**Issue by zengyifan1** [cabooster/DeepCAD-RT#6]
hi, these two days we try to establish your brilliant DeepCAD tool, we have followed your steps to install everything we need. However, we encounter a problem when we try to train the demo data, it raise Tifffileerror ('not a TIFF file'), then we try other tiff data, it continue to report this error.

(deepcad) dell@dell-Precision-3640-Tower:~/Python_For_DeepCap/DeepCAD/DeepCAD_pytorch$ python script.py train
the parameter of your training ----->
Namespace(GPU=0, b1=0.5, b2=0.999, batch_size=1, cuda=False, datasets_folder='DataForPytorch', datasets_path='datasets', epoch=0, gap_h=40, gap_s=40, gap_w=40, img_h=40, img_s=40, img_w=40, lr=5e-05, n_epochs=20, normalize_factor=1, output_dir='./results', pth_path='pth', select_img_num=150, train_datasets_size=150)
list(os.walk(im_folder, topdown=False)) ----->  [('datasets//DataForPytorch', [], ['DownloadedData', 'M1_UG.tiff'])]
stack_num ----->  2
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/deepcad/lib/python3.6/site-packages/tifffile/tifffile.py", line 2236, in __init__
    byteorder = {b'II': '<', b'MM': '>'}[header[:2]]
KeyError: b'\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 66, in <module>
    name_list, noise_img, coordinate_list = train_preprocess_lessMemoryMulStacks(opt)
  File "/home/dell/Python_For_DeepCap/DeepCAD/DeepCAD_pytorch/data_process.py", line 263, in train_preprocess_lessMemoryMulStacks
    noise_im = tiff.imread(im_dir)
  File "/home/dell/anaconda3/envs/deepcad/lib/python3.6/site-packages/tifffile/tifffile.py", line 715, in imread
    with TiffFile(files, **kwargs_file) as tif:
  File "/home/dell/anaconda3/envs/deepcad/lib/python3.6/site-packages/tifffile/tifffile.py", line 2238, in __init__
    raise TiffFileError('not a TIFF file')
tifffile.tifffile.TiffFileError: not a TIFF file

**Comment by cabooster** [comment]
Hi, zengyifan1. This error was caused by the non-tif file `datasets//DataForPytorch`. It's just a placeholder file since GitHub does not allow empty folders. You should delete it and run the training command again. I hope this could be helpful.

**Comment by zengyifan1** [comment]
Thank you very much! The system can work now!
